### ISSUE TITLE
missing deploy info for bosh-lite: warden

### ISSUE THREAD

**Issue by tyyko** [logsearch/logsearch-for-cloudfoundry#31]
As the title:
```
  jobs:
   - name: ingestor_cloudfoundry
     release: logsearch-for-cloudfoundry
     templates:
   - name: ingestor_cloudfoundry-firehose
     instances: 1
     resource_pool: small_z1
     networks: z1
     persistent_disk: 0

   properties:
     ingestor_cloudfoundry-firehose:
       uaa-endpoint: "https://uaa.10.244.0.34.xip.io/oauth/authorize"
       doppler-endpoint: "wss://doppler.10.244.0.34.xip.io"
       skip-ssl-validation: true
       firehose-user: admin
       firehose-password: admin
       syslog-server: "10.244.10.6:514"
```
Is not for bosh-lite

``` resource_pool: small_z1 ``` should be ```  resource_pool: warden ```

``` networks: z1 ``` should be ??

Thanks

Edit: 

Tried the /logsearch-for-cloudfoundry-boshrelease and I got this:

```
Started preparing configuration > Binding configuration. Failed: Error filling in template `ingestor_cloudfoundry-firehose_ctl' for `ingestor_cloudfoundry/0' (line 21: Can't find property `["ingestor_cloudfoundry-firehose.cf-domain"]') (00:00:00)

Error 100: Error filling in template `ingestor_cloudfoundry-firehose_ctl' for `ingestor_cloudfoundry/0' (line 21: Can't find property `["ingestor_cloudfoundry-firehose.cf-domain"]')
```

more debug info at http://pastebin.com/DPeHtnKN

**Comment by simonjohansson** [comment]
Hi!

```
resource_pool: small_z1 should be resource_pool: warden

networks: z1 should be ??
```

That looks to be from a "normal" CF deployment rather than a bosh-lite deployment.

My suspicion is that more people are going to deploy this on a real deployment than a bosh-lite one, so to me it makes more sense to show that setup in the README.

Docs should be clear about how to deploy in real deployment vs bosh-lite though to remove any confusion.

But to answer your question, network and resource_pool should be whether you have named your resource_pool and network to in your manifest:) 

```
Can't find property `["ingestor_cloudfoundry-firehose.cf-domain"]') 
```

This means that you need to specify that property in your manifest, i.e

```
...
...lots and lots of bosh deployment manifest stuff.
...
properties:
    ingestor_cloudfoundry-firehose:
       cf-domain: wakawaka.domain.com
```

Your domain will likely be "10.244.0.34.xip.io" if you have not changed the ip of the bosh-lite vm.

You can see all the different properties and desc for them in the job spec,
https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/spec


Hope that helps!

**Comment by tyyko** [comment]
Many Thanks for your help, I got it working with:

```
jobs:
   - name: ingestor_cloudfoundry
     release: logsearch-for-cloudfoundry
     templates:
   - name: ingestor_cloudfoundry-firehose
     instances: 1
     resource_pool: warden
      networks:
      - name: default
     persistent_disk: 0

   properties:
     ingestor_cloudfoundry-firehose:
       uaa-endpoint: "https://uaa.10.244.0.34.xip.io/oauth/authorize"
       doppler-endpoint: "wss://doppler.10.244.0.34.xip.io"
       skip-ssl-validation: true
       firehose-user: admin
       firehose-password: admin
       syslog-server: "10.244.2.14:5514"
       cf-domain: 10.244.0.34.xip.io
```
I may be useful to point this too on the readme, for bosh-lite users that want to test before deploying in production!

I have other questions but I'm opening different issues to keep the topics separated an searchable!
